// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ5FaEy6997IESnCueNk8KjmYt3y5gIiE',
    appId: '1:471070913152:web:47f2030c50eab10d78ac65',
    messagingSenderId: '471070913152',
    projectId: 'task2-62f54',
    authDomain: 'task2-62f54.firebaseapp.com',
    storageBucket: 'task2-62f54.firebasestorage.app',
    measurementId: 'G-1YGKHDLKNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEMzbK7c1beLt3C2QC1cskSxOBZgx7FIo',
    appId: '1:471070913152:android:e329469e0adc377f78ac65',
    messagingSenderId: '471070913152',
    projectId: 'task2-62f54',
    storageBucket: 'task2-62f54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5c8ry42tyFGNpHAVcAQVB9WBZmLuCc-k',
    appId: '1:471070913152:ios:a01a9b95ba78ba2778ac65',
    messagingSenderId: '471070913152',
    projectId: 'task2-62f54',
    storageBucket: 'task2-62f54.firebasestorage.app',
    androidClientId: '471070913152-nt20k1799jh5lbnb1h4o68unuupkt3oq.apps.googleusercontent.com',
    iosClientId: '471070913152-thuu0hm3fm2rlkp6u8s8j5voaiqmu2us.apps.googleusercontent.com',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5c8ry42tyFGNpHAVcAQVB9WBZmLuCc-k',
    appId: '1:471070913152:ios:a01a9b95ba78ba2778ac65',
    messagingSenderId: '471070913152',
    projectId: 'task2-62f54',
    storageBucket: 'task2-62f54.firebasestorage.app',
    androidClientId: '471070913152-nt20k1799jh5lbnb1h4o68unuupkt3oq.apps.googleusercontent.com',
    iosClientId: '471070913152-thuu0hm3fm2rlkp6u8s8j5voaiqmu2us.apps.googleusercontent.com',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ5FaEy6997IESnCueNk8KjmYt3y5gIiE',
    appId: '1:471070913152:web:be7a1d6b400d32ac78ac65',
    messagingSenderId: '471070913152',
    projectId: 'task2-62f54',
    authDomain: 'task2-62f54.firebaseapp.com',
    storageBucket: 'task2-62f54.firebasestorage.app',
    measurementId: 'G-F0B7F36QBB',
  );
}
